export default {
    voyagerColors: [
        { name: 'Blue-Gray', key: 'BG', code: '#99c' },
        { name: 'Lightblue', key: 'LB', code: '#99f' },
        { name: 'Lilac', key: 'FL', code: '#c9c' },

        { name: 'Pink', key: 'PI', code: '#c69' },
        { name: 'Light-Pink', key: 'LP', code: '#f9c' },

        { name: 'Russet', key: 'RB', code: '#c66' },
        { name: 'Apricot', key: 'AP', code: '#f96' },

        { name: 'Beige', key: 'BE', code: '#fc9' },
        { name: 'Light-Orange', key: 'HO', code: '#f7c64a' },
        { name: 'Orange', key: 'OR', code: '#f90' }
    ],
    ussColors: [
        { name: 'Blue-1', key: 'b1', code: '#9cf' },
        { name: 'Blue-2', key: 'b2', code: '#39c' },
        { name: 'Blue-3', key: 'b3', code: '#069' },
        { name: 'Blue-4', key: 'b4', code: '#036' },

        { name: 'Green-1', key: 'g1', code: '#cdb' },
        { name: 'Green-2', key: 'g2', code: '#0c9' },
        { name: 'Green-3', key: 'g3', code: '#099' },
        { name: 'Green-4', key: 'g4', code: '#066' }
    ],
    paddColors: [
        { name: 'golden-tanoi', key: 'p1', code: '#fc6' },
        { name: 'cold-gray', key: 'p2', code: '#999' },
        { name: 'chestnut-rose', key: 'p3', code: '#c66' },
        { name: 'lilac', key: 'p4', code: '#c9c' },
        { name: 'anakiwa', key: 'p5', code: '#9cf' },
        { name: 'atomic-tangerine', key: 'p6', code: '#f90' }
    ],
    year2357Colors: [
        { name: 'pale-canary', key: 'pc', code: '#ff9' },
        { name: 'golden-tanoi', key: 'gt', code: '#fc6' },
        { name: 'neon-carrot', key: 'nc', code: '#f93' },
        { name: 'eggplant', key: 'ep', code: '#646' },
        { name: 'lilac', key: 'lc', code: '#c9c' },
        { name: 'anakiwa', key: 'ak', code: '#9cf' },
        { name: 'mariner', key: 'mi', code: '#36c' },
        { name: 'baltic-blue', key: 'bt', code: '#069' }
    ],
    year2369Colors: [
        { name: 'blue-bell', key: 'bb', code: '#99c' },
        { name: 'melrose', key: 'mr', code: '#99f' },
        { name: 'lilac', key: 'lc', code: '#c9c' },
        { name: 'hopbush', key: 'hb', code: '#c69' },
        { name: 'chestnut-rose', key: 'cr', code: '#c66' },
        { name: 'orange-peel', key: 'op', code: '#f96' },
        { name: 'atomic-tangerine', key: 'at', code: '#f90' },
        { name: 'golden-tanoi', key: 'gt', code: '#fc6' }
    ],
    year2375Colors: [
        { name: 'danub', key: 'db', code: '#68c' },
        { name: 'indigo', key: 'ig', code: '#45b' },
        { name: 'lavender-purple', key: 'lr', code: '#97a' },
        { name: 'cosmic', key: 'cs', code: '#746' },
        { name: 'red-damask', key: 'rd', code: '#d64' },
        { name: 'medium-carmine', key: 'ca', code: '#a53' },
        { name: 'bourbon', key: 'br', code: '#b62' },
        { name: 'sandy-brown', key: 'sb', code: '#e95' }
    ],
    year2379Colors: [
        { name: 'periwinkle', key: 'pw', code: '#cdf' },
        { name: 'dodger-blue', key: 'dg', code: '#59f' },
        { name: 'dodger-blue-alt', key: 'dd', code: '#36f' },
        { name: 'blue', key: 'bl', code: '#01e' },
        { name: 'navy-blue', key: 'nb', code: '#008' },
        { name: 'husk', key: 'hs', code: '#ba5' },
        { name: 'rust', key: 'rs', code: '#b41' },
        { name: 'tamarillo', key: 'tm', code: '#821' }
    ],
    odysseyNormalColors: [
        { name: 'offline', key: 'bs', code: '#4d4d4d' },
        { name: 'dark-1', key: 'cb', code: '#133d87' },
        { name: 'frame', key: 'ib', code: '#2350b5' },
        { name: 'light-1', key: 'ob', code: '#335da7' },
        { name: 'light-2', key: 'eb', code: '#4a72ca' },
        { name: 'active', key: 'vs', code: '#97c3e1' }
    ],
    odysseyGrayModeColors: [
        { name: 'offline', key: 'bs', code: '#4d4d4d' },
        { name: 'dark-1', key: 'd1', code: '#808080' },
        { name: 'frame', key: 'fm', code: '#808080' },
        { name: 'light-1', key: 'l1', code: '#808080' },
        { name: 'light-2', key: 'l2', code: '#808080' },
        { name: 'active', key: 'ac', code: '#ccc' },
    ],
    odysseyBlueAlertColors: [
        { name: 'offline', key: 'bs', code: '#4d4d4d' },
        { name: 'dark-1', key: 'tb', code: '#00c' },
        { name: 'frame', key: 'ur', code: '#03f' },
        { name: 'light-1', key: 'mb', code: '#06f' },
        { name: 'light-2', key: 'ab', code: '#4159ff' },
        { name: 'active', key: 'vb', code: '#8d9bff' }
    ],
    odysseyYellowAlertColors: [
        { name: 'offline', key: 'bs', code: '#4d4d4d' },
        { name: 'dark-1', key: 'dr', code: '#664406' },
        { name: 'frame', key: 'on', code: '#996509' },
        { name: 'light-1', key: 'so', code: '#cc870c' },
        { name: 'light-2', key: 'ag', code: '#ffa90f' },
        { name: 'active', key: 'my', code: '#ffd966' }
    ],
    odysseyRedAlertColors: [
        { name: 'offline', key: 'bs', code: '#4d4d4d' },
        { name: 'dark-1', key: 'bo', code: '#600' },
        { name: 'frame', key: 'cm', code: '#900' },
        { name: 'light-1', key: 'rg', code: '#c00' },
        { name: 'light-2', key: 'pr', code: '#f00' },
        { name: 'active', key: 'vp', code: '#ff9191' }
    ],
    allColors: [
        { name: 'black', key: 'black', font: '#ddd', code: '#000' },
        { name: 'navy-blue', key: 'navy-blue', font: '#ddd', code: '#008' },
        { name: 'strong-blue', key: 'strong-blue', font: '#000', code: '#00c' },
        { name: 'pure-blue', key: 'pure-blue', font: '#000', code: '#00f' },
        { name: 'blue', key: 'blue', font: '#000', code: '#01e' },
        { name: 'dark-midnight-blue', key: 'dark-midnight-blue', font: '#ddd', code: '#036' },
        { name: 'nearly-pure-blue', key: 'nearly-pure-blue', font: '#000', code: '#03f' },
        { name: 'very-dark-cyan', key: 'very-dark-cyan', font: '#000', code: '#066' },
        { name: 'baltic-blue', key: 'baltic-blue', font: '#000', code: '#069' },
        { name: 'mostly-pure-blue', key: 'mostly-pure-blue', font: '#000', code: '#06f' },
        { name: 'dark-cyan', key: 'dark-cyan', font: '#000', code: '#099' },
        { name: 'carribean-green', key: 'carribean-green', font: '#000', code: '#0c9' },
        { name: 'pure-green', key: 'pure-green', font: '#000', code: '#0f0' },
        { name: 'monochrome-green-2', key: 'monochrome-green-2', font: '#000', code: '#0f3' },
        { name: 'monochrome-green-3', key: 'monochrome-green-3', font: '#000', code: '#0f6' },
        { name: 'cyan-blue', key: 'cyan-blue', font: '#000', code: '#133d87' },
        { name: 'main-blue', key: 'main-blue', font: '#000', code: '#2350b5' },
        { name: 'monochrome-black', key: 'monochrome-black', font: '#ddd', code: '#282828' },
        { name: 'very-dark-red', key: 'very-dark-red', font: '#ddd', code: '#300' },
        { name: 'dark-moderate-blue', key: 'dark-moderate-blue', font: '#000', code: '#335da7' },
        { name: 'azure-blue', key: 'azure-blue', font: '#ddd', code: '#369' },
        { name: 'mariner', key: 'mariner', font: '#000', code: '#36c' },
        { name: 'dodger-blue-alt', key: 'dodger-blue-alt', font: '#000', code: '#36f' },
        { name: 'bavaria-blue', key: 'bavaria-blue', font: '#000', code: '#39c' },
        { name: 'monochrome-green-1', key: 'monochrome-green-1', font: '#000', code: '#3f0' },
        { name: 'monochrome-apple', key: 'monochrome-apple', font: '#000', code: '#3f3' },
        { name: 'saturated-blue', key: 'saturated-blue', font: '#000', code: '#4159ff' },
        { name: 'indigo', key: 'indigo', font: '#000', code: '#45b' },
        { name: 'moderate-blue', key: 'moderate-blue', font: '#000', code: '#4a72ca' },
        { name: 'black-swan', key: 'black-swan', font: '#000', code: '#4d4d4d' },
        { name: 'dodger-blue', key: 'dodger-blue', font: '#000', code: '#59f' },
        { name: 'blood-red', key: 'blood-red', font: '#ddd', code: '#600' },
        { name: 'dark-brown', key: 'dark-brown', font: '#000', code: '#664406' },
        { name: 'eggplant', key: 'eggplant', font: '#ddd', code: '#646' },
        { name: 'lead-gray', key: 'lead-gray', font: '#000', code: '#666' },
        { name: 'danub', key: 'danub', font: '#000', code: '#68c' },
        { name: 'cosmic', key: 'cosmic', font: '#000', code: '#746' },
        { name: 'steel-gray', key: 'steel-gray', font: '#000', code: '#808080' },
        { name: 'tamarillo', key: 'tamarillo', font: '#ddd', code: '#821' },
        { name: 'very-light-blue', key: 'very-light-blue', font: '#000', code: '#8d9bff' },
        { name: 'chelsea-gem', key: 'chelsea-gem', font: '#ddd', code: '#965032' },
        { name: 'very-soft-blue', key: 'very-soft-blue', font: '#000', code: '#97c3e1' },
        { name: 'crimson-red', key: 'crimson-red', font: '#ddd', code: '#900' },
        { name: 'orange-brown', key: 'orange-brown', font: '#000', code: '#996509' },
        { name: 'lavender-purple', key: 'lavender-purple', font: '#000', code: '#97a' },
        { name: 'cold-gray', key: 'cold-gray', font: '#000', code: '#999' },
        { name: 'anakiwa', key: 'anakiwa', font: '#000', code: '#9cf' },
        { name: 'blue-bell', key: 'blue-bell', font: '#000', code: '#99c' },
        { name: 'melrose', key: 'melrose', font: '#000', code: '#99f' },
        { name: 'medium-carmine', key: 'medium-carmine', font: '#000', code: '#a53' },
        { name: 'rust', key: 'rust', font: '#000', code: '#b41' },
        { name: 'bourbon', key: 'bourbon', font: '#000', code: '#b62' },
        { name: 'husk', key: 'husk', font: '#000', code: '#ba5' },
        { name: 'free-speech-red', key: 'free-speech-red', font: '#ddd', code: '#c80000' },
        { name: 'rangoon-red', key: 'rangoon-red', font: '#ddd', code: '#c00' },
        { name: 'chestnut-rose', key: 'chestnut-rose', font: '#000', code: '#c66' },
        { name: 'hopbush', key: 'hopbush', font: '#000', code: '#c69' },
        { name: 'strong-orange', key: 'strong-orange', font: '#000', code: '#cc870c' },
        { name: 'desaturated-red', key: 'desaturated-red', font: '#000', code: '#c99' },
        { name: 'lilac', key: 'lilac', font: '#000', code: '#c9c' },
        { name: 'chinese-silver', key: 'chinese-silver', font: '#000', code: '#ccc' },
        { name: 'grayish-green', key: 'grayish-green', font: '#000', code: '#cdb' },
        { name: 'periwinkle', key: 'periwinkle', font: '#000', code: '#cdf' },
        { name: 'red-damask', key: 'red-damask', font: '#000', code: '#d64' },
        { name: 'very-light-gray', key: 'very-light-gray', font: '#000', code: '#eee' },
        { name: 'sandy-brown', key: 'sandy-brown', font: '#000', code: '#e95' },
        { name: 'sunset-orange', key: 'sunset-orange', font: '#000', code: '#f55' },
        { name: 'pure-red', key: 'pure-red', font: '#000', code: '#f00' },
        { name: 'bittersweet', key: 'bittersweet', font: '#000', code: '#f66' },
        { name: 'bright-coral', key: 'bright-coral', font: '#000', code: '#f77' },
        { name: 'light-orange', key: 'light-orange', font: '#000', code: '#f7c64a' },
        { name: 'very-light-red', key: 'very-light-red', font: '#000', code: '#f88' },
        { name: 'very-light-pink', key: 'very-light-pink', font: '#000', code: '#ff9191' },
        { name: 'atomic-tangerine', key: 'atomic-tangerine', font: '#000', code: '#f90' },
        { name: 'neon-carrot', key: 'neon-carrot', font: '#000', code: '#f93' },
        { name: 'orange-peel', key: 'orange-peel', font: '#000', code: '#f96' },
        { name: 'pale-magenta', key: 'pale-magenta', font: '#000', code: '#f9c' },
        { name: 'light-salmon-pink', key: 'light-salmon-pink', font: '#000', code: '#f99' },
        { name: 'all-gold', key: 'all-gold', font: '#000', code: '#ffa90f' },
        { name: 'patient-pink', key: 'patient-pink', font: '#000', code: '#faa' },
        { name: 'amber', key: 'amber', font: '#000', code: '#ffb000' },
        { name: 'pale-red', key: 'pale-red', font: '#000', code: '#fbb' },
        { name: 'light-amber', key: 'light-amber', font: '#000', code: '#fc0' },
        { name: 'golden-tanoi', key: 'golden-tanoi', font: '#000', code: '#fc6' },
        { name: 'peach-orange', key: 'peach-orange', font: '#000', code: '#fc9' },
        { name: 'light-red', key: 'light-red', font: '#000', code: '#fcc' },
        { name: 'medium-yellow', key: 'medium-yellow', font: '#000', code: '#ffd966' },
        { name: 'very-pale-red', key: 'very-pale-red', font: '#000', code: '#fdd' },
        { name: 'laser-lemon', key: 'laser-lemon', font: '#000', code: '#ff6' },
        { name: 'pale-canary', key: 'pale-canary', font: '#000', code: '#ff9' },
        { name: 'white', key: 'white', font: '#000', code: '#fff' },
    ]
};