name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate static files
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run docs:build

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs/.vuepress/dist
        git init
        git add -A
        git config --local user.email "xiphoseer@mailbox.org"
        git config --local user.name "GitHub Actions (Xiphoseer)"
        git commit -m 'deploy'

    - name: Upload to GH pages
      uses: actions/upload-pages-artifact@v0.1.0
      with:
        path: ./docs/.vuepress/dist
